export const data = {
  scheduledShipDate: "2025-08-22 19:35",
  from: {
    attention: "John Doe",
    company: "Example Corp",
    address1: "3925 Steeles Ave E.",
    address2: "Unit 1",
    city: "Brampton",
    province: "ON",
    country: "CA",
    zip: "L6T 5W5",
    email: "john.doe@example.com",
    phone: "1234567890",
    instructions: "Leave at the front desk",
    residential: false,
    tailgateRequired: false,
    confirmDelivery: true,
    notifyRecipient: true,
  },
  to: {
    attention: "Jane Smith",
    company: "Another Corp",
    address1: "390 Chrysler drive",
    address2: " ",
    city: "Brampton",
    province: "ON",
    country: "CA",
    zip: "L6S 6G3",
    email: "jane.smith@example.com",
    phone: "9876543210",
    instructions: "Deliver to the back entrance",
    residential: false,
    tailgateRequired: false,
    confirmDelivery: true,
    notifyRecipient: true,
  },
  packagingUnit: "Metric",
  packages: {
    type: "Package",
    packages: [
      {
        height: 10,
        length: 20,
        width: 15,
        dimensionUnit: "cm",
        weight: 5,
        weightUnit: "kg",
        insuranceAmount: 100,
        description: "Electronics",
      },
    ],
  },
  reference1: "Order12345",
  reference2: "PO98765",
  reference3: "INV001",
  signatureRequired: "No",
  insuranceType: "None",
  pickup: {
    contactName: "Warehouse Manager",
    phoneNumber: "5551234567",
    pickupDate: "2025-09-23",
    pickupTime: "22:53",
    closingTime: "23:53",
    location: "Receiving",
    instructions: "Use loading dock",
  },
};
